

filter {
  grok {
    match => {
      message => "%{WORD}%{SPACE}%{TIMESTAMP_ISO8601:logdate}\s\[%{GREEDYDATA}]%{SPACE}%{GREEDYDATA}: ##MESSAGE## %{GREEDYDATA:message}"
    }
    overwrite => ["message"]
  }
  date {
    match => ["logdate", "yyyy-MM-dd HH:mm:ss,SSS", "ISO8601"]
  }
  json {
    source => "message"
  }
  fingerprint {
    source => ["logdate", "message", "app_name"]
    target => "my_unique_id"                
    method => "SHA1"
	concatenate_all_fields => true
  }
  mutate {
    add_field => {
      "[ext][full_display_id]" => "com.lamar:%{[ext][display_id]}"
    }
  }
  ruby {
    code => '
      if event.get("[ext][display_id]")
        event.set("[ext][plant]", event.get("[ext][display_id]")[0,3])
      end
    '
  }
}


